//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsClient.IncrServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IncrServiceReference.IIncrService", CallbackContract=typeof(EventsClient.IncrServiceReference.IIncrServiceCallback))]
    public interface IIncrService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncrService/Incr", ReplyAction="http://tempuri.org/IIncrService/IncrResponse")]
        void Incr();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncrService/Incr", ReplyAction="http://tempuri.org/IIncrService/IncrResponse")]
        System.Threading.Tasks.Task IncrAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncrService/Decr", ReplyAction="http://tempuri.org/IIncrService/DecrResponse")]
        void Decr();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncrService/Decr", ReplyAction="http://tempuri.org/IIncrService/DecrResponse")]
        System.Threading.Tasks.Task DecrAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncrService/SubscribeUpdatedEvent", ReplyAction="http://tempuri.org/IIncrService/SubscribeUpdatedEventResponse")]
        void SubscribeUpdatedEvent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncrService/SubscribeUpdatedEvent", ReplyAction="http://tempuri.org/IIncrService/SubscribeUpdatedEventResponse")]
        System.Threading.Tasks.Task SubscribeUpdatedEventAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIncrServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IIncrService/Updated")]
        void Updated(int counter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIncrServiceChannel : EventsClient.IncrServiceReference.IIncrService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IncrServiceClient : System.ServiceModel.DuplexClientBase<EventsClient.IncrServiceReference.IIncrService>, EventsClient.IncrServiceReference.IIncrService {
        
        public IncrServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public IncrServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public IncrServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public IncrServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public IncrServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Incr() {
            base.Channel.Incr();
        }
        
        public System.Threading.Tasks.Task IncrAsync() {
            return base.Channel.IncrAsync();
        }
        
        public void Decr() {
            base.Channel.Decr();
        }
        
        public System.Threading.Tasks.Task DecrAsync() {
            return base.Channel.DecrAsync();
        }
        
        public void SubscribeUpdatedEvent() {
            base.Channel.SubscribeUpdatedEvent();
        }
        
        public System.Threading.Tasks.Task SubscribeUpdatedEventAsync() {
            return base.Channel.SubscribeUpdatedEventAsync();
        }
    }
}
